### ISSUE TITLE
Error contacting api

### ISSUE THREAD

**Issue by CoelacanthsKill** [mrwnwttk/audius-dl#1] opened 2021-04-03 16:35 UTC
Following install instructions, I am getting an API contact error. 

pat@DESKTOP-455TDJM:~/Audius/audius-dl$ python3 audius-dl.py https://audius.co/deadmau5/deadmau5-unlucky-work-in-progress-333797
Error occurred while contacting api.audius.co! Trying again in two seconds...
Error occurred while contacting api.audius.co! Trying again in two seconds...
Error occurred while contacting api.audius.co! Trying again in two seconds...
Error occurred while contacting api.audius.co! Trying again in two seconds...
Error occurred while contacting api.audius.co! Trying again in two seconds...

**Comment by CoelacanthsKill** [comment] 2021-04-03 16:54
Trying a different track with the same artist: 

python3 audius-dl.py https://audius.co/deadmau5/deadmau5-meowinghtons-normal-hacks-333876
API endpoint: https://dn2.monophonic.digital
Number of segments: 36
An exception occurred while trying to resolve the link, trying again in two seconds...
An exception occurred while trying to resolve the link, trying again in two seconds...
An exception occurred while trying to resolve the link, trying again in two seconds...

**Comment by mrwnwttk** [comment] 2021-04-03 16:58
dn2.monophonic.digital is acting up and not accepting connections for whatever reason.

```
HTTPSConnectionPool(host='127.0.0.1', port=32662): Max retries exceeded with url: /v1/tracks/QxamW (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000254C4071400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

That issue seems to be on the server side so I'd just wait a bit, not much we can do about it. You don't get a say in what API endpoint is assigned to each user. What a load of BS.

Try again in an hour or two and let me know if it's still not working.

**Comment by CoelacanthsKill** [comment] 2021-04-03 17:26
From what I've seen nothing is centralized, which complicates everything. How pleasant.

**Comment by mrwnwttk** [comment] 2021-04-04 10:08
Yup, it's all decentralized.  Just tried it again and everything seems to be working as intended. Can you confirm that?

**Closed as completed** 2021-07-06 08:56 UTC
